version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
    - "8080:8080"
    depends_on: 
      - "db"
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goapi
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: